package packages

func Problem() {
	// 5 PHILOSOPHERS SHARING CHOPSTICKS, WITH 1 CHOPSTICK BETWEEN EACH ADJACENT PAIR OF PHILOSOPHERS

	// EAT ONLY 3 TIMES

	// PICK UP THE CHOPSTICKS IN ANY ORDER

	// TO EAT, MUST GET PERMISSION FROM THE HOST WHICH EXECUTES ITS OWN GOROUTINE

	// THE HOST ALLOWS NO MORE THAN 2 PHILOSOPHERS TO EAT CONCURRENTLY

	// PHILOSOPHERS ARE NUMBERED 1 TO 5

	// WHEN STARTS EATING (AFTER IT HAS OBTAINED NECESSARY LOCKS) IT PRINTS "STARTING TO EAT <NUMBER>"

	// WHEN FINISHES EATING (BEFORE IT HAS RELEASED ITS LOCK) IT PRINTS "FINISHING EATING <NUMBER>"
}